version: '3'

services:
  wp-listener:
    build: wp-listener
    command: node_modules/.bin/nodemon server.js
    env_file:
      - ./wp-listener/variables.env
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ./wp-listener:/home/app-user/app
      - /home/app-user/app/node_modules

  hugo-builder:
    build: hugo-builder
    command: node_modules/.bin/nodemon server.js
    env_file:
      - ./hugo-builder/variables.env
    environment:
      NODE_ENV: development
    ports:
      - '3030:3030'
    volumes:
      - ./hugo-builder:/home/app-user/app
      - /home/app-user/app/node_modules
